<html>
<head>
<title>WarezPress Create new post</title>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<link rel="stylesheet" href="<?= base_url() ?>resources/markitup/skins/markitup/style.css">
<link rel="stylesheet" href="<?= base_url() ?>resources/markitup/sets/html/style.css">
<script type="text/javascript" src="<?= base_url() ?>resources/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="<?= base_url() ?>resources/markitup/sets/html/set.js"></script>
<script type="text/javascript" src="<?= base_url() ?>resources/markitup/sets/html/wrzcms.js"></script>
<script type="text/javascript" >
   $(document).ready(function() {
      $("#long").markItUp(mySettings);
   });
</script>

<script type="text/javascript" >
   $(document).ready(function() {
      $("#links").markItUp(wrzCMSFilehosts);
   });
</script>
</head>
<body>
<h1><?php echo $title;?></h1>

<?php
echo form_open('hood/downloads/create');
echo "<p><label for='ptitle'>Title (Pretty url will be generated by the system itself )</label><br/>";
// will probably add a feature where it shows the seo url like wp :P in future
$data = array('name'=>'title','id'=>'ptitle','size'=>'72');
echo form_input($data) ."</p>";


echo "<p><label for='category_id'>Category </label><br/>";
echo form_dropdown('category_id',$wareztype) ."</p>";


echo "<p><label for='long'>Info and ScreenShots</label><br/>";
$data = array('name'=>'body','id'=>'long','rows'=>5, 'cols'=>'40');
echo form_textarea($data) ."</p>";

//echo "<p><label for='links'>Download Links (File Hosts) </label><br/>";
$data = array('name'=>'body2','id'=>'links','rows'=>5, 'cols'=>'20');
echo form_textarea($data) ."</p>";

echo "<p><label for='status'>Status</label><br/>";
$options = array('draft' => 'draft', 'published' => 'published');
echo form_dropdown('status',$options) ."</p>";


echo form_submit('submit','create post');
echo form_close();

?>
</body>
</html>
